version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: shop-co
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - '5433:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: shop-co-postgres-db

